From: "Luke Ehresman" <lehresma@css.tayloru.edu>
Subject: Test BASE64 Message
To: luke@usa.om.org
Date: Tue, Aug 27 2002 11:23:14 EDT
MIME-Version: 1.0
Content-Type: multipart/mixed
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; boundary="CENTRALLIX_ROCKS_MY_WORLD"
X-Mailer: Luke's Keyboard (v1.0)

--CENTRALLIX_ROCKS_MY_WORLD
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline; filename="bob.txt";

This message is supposed to be used as a test of base64 decoding.
--CENTRALLIX_ROCKS_MY_WORLD
Content-Type: text/plain
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="fred.txt";

QWJDZEVmR2hJaktsTW5PcFFyU3RVdld4WXoKVGhpcyBpcyBhIHRlc3QgbWVzc2FnZSB0aG
F0IGhhcyBiZWVuIGJhc2U2NCBlbmNvZGVkLiAgSG9wZWZ1bGx5CmV2ZXJ5dGhpbmcgY29t
ZXMgb3V0IE9LLiAgVGhpcyB3aWxsIGJlIHVzZWQgdG8gdGVzdCB0aGUgYmFzZTY0CmRlY2
9kaW5nIGNhcGFiaWxpdGllcyBvZiB0aGUgQ2VudHJhbGxpeCBNSU1FIHBhcnNlci4gIEhl
cmUgaXMKYW5vdGhlciBjb3B5IG9mIHRoZSBhbHBoYWJldCEhCkEgRCBHIEogTSBQIFMgVi
BZCkIgRSBIIEsgTiBRIFQgVyBaCkMgRiBJIEwgTyBSIFUgWApXZWxsLCBJIGd1ZXNzIHRo
YXQncyBhbGwgSSBoYXZlIHRvIHNheSBhYm91dCB0aGF0LiAgU2VlIHlvdSBhcm91bmQhCk
x1a2U=
--CENTRALLIX_ROCKS_MY_WORLD--

