/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

//#include "mount.h"

#ifndef XDR_FHANDLE
#define XDR_FHANDLE
bool_t
xdr_fhandle (XDR *xdrs, fhandle objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, FHSIZE))
		 return FALSE;
	return TRUE;
}
#endif

bool_t
xdr_fhstatus (XDR *xdrs, fhstatus *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case 0:
		 if (!xdr_fhandle (xdrs, objp->fhstatus_u.directory))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_dirpath (XDR *xdrs, dirpath *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_name (XDR *xdrs, name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MNTNAMLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountlist_item (XDR *xdrs, mountlist_item *objp)
{
	register int32_t *buf;

	 if (!xdr_name (xdrs, &objp->hostname))
		 return FALSE;
	 if (!xdr_dirpath (xdrs, &objp->directory))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nextentry, sizeof (mountlist_item), (xdrproc_t) xdr_mountlist_item))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountlist (XDR *xdrs, mountlist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (mountlist_item), (xdrproc_t) xdr_mountlist_item))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_groups_item (XDR *xdrs, groups_item *objp)
{
	register int32_t *buf;

	 if (!xdr_name (xdrs, &objp->grname))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->grnext, sizeof (groups_item), (xdrproc_t) xdr_groups_item))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_groups (XDR *xdrs, groups *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (groups_item), (xdrproc_t) xdr_groups_item))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exportlist_item (XDR *xdrs, exportlist_item *objp)
{
	register int32_t *buf;

	 if (!xdr_dirpath (xdrs, &objp->filesys))
		 return FALSE;
	 if (!xdr_groups (xdrs, &objp->groups))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (exportlist_item), (xdrproc_t) xdr_exportlist_item))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exportlist (XDR *xdrs, exportlist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (exportlist_item), (xdrproc_t) xdr_exportlist_item))
		 return FALSE;
	return TRUE;
}
