/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MOUNT_H_RPCGEN
#define _MOUNT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MNTPATHLEN 1024
#define MNTNAMLEN 255
#ifndef FHSIZE
#define FHSIZE 32
#endif

#ifndef FHANDLE
typedef char fhandle[FHSIZE];
#define FHANDLE
#endif

struct fhstatus {
	u_int status;
	union {
		fhandle directory;
	} fhstatus_u;
};
typedef struct fhstatus fhstatus;

typedef char *dirpath;

typedef char *name;

struct mountlist_item {
	name hostname;
	dirpath directory;
	struct mountlist_item *nextentry;
};
typedef struct mountlist_item mountlist_item;

typedef mountlist_item *mountlist;

struct groups_item {
	name grname;
	struct groups_item *grnext;
};
typedef struct groups_item groups_item;

typedef groups_item *groups;

struct exportlist_item {
	dirpath filesys;
	groups groups;
	struct exportlist_item *next;
};
typedef struct exportlist_item exportlist_item;

typedef exportlist_item *exportlist;

#define MOUNTPROG 100005
#define MOUNTVERS 1

#define MOUNTPROC_NULL 0
#define MOUNTPROC_MNT 1
#define MOUNTPROC_DUMP 2
#define MOUNTPROC_UMNT 3
#define MOUNTPROC_UMNTALL 4
#define MOUNTPROC_EXPORT 5

extern  bool_t xdr_fhandle (XDR *, fhandle);
extern  bool_t xdr_fhstatus (XDR *, fhstatus*);
extern  bool_t xdr_dirpath (XDR *, dirpath*);
extern  bool_t xdr_name (XDR *, name*);
extern  bool_t xdr_mountlist_item (XDR *, mountlist_item*);
extern  bool_t xdr_mountlist (XDR *, mountlist*);
extern  bool_t xdr_groups_item (XDR *, groups_item*);
extern  bool_t xdr_groups (XDR *, groups*);
extern  bool_t xdr_exportlist_item (XDR *, exportlist_item*);
extern  bool_t xdr_exportlist (XDR *, exportlist*);


#ifdef __cplusplus
}
#endif

#endif /* !_MOUNT_H_RPCGEN */
